# Generated by Django 5.2.7 on 2026-01-13 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Andou',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.CharField(max_length=10, verbose_name='年份(如：乙巳年)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('item', models.CharField(max_length=50, verbose_name='項目')),
                ('name', models.CharField(max_length=100, verbose_name='姓名')),
                ('address', models.CharField(max_length=255, verbose_name='地址')),
                ('payment_status', models.BooleanField(default=False, verbose_name='繳費狀態')),
                ('remark', models.TextField(blank=True, verbose_name='備註')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Committee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.CharField(max_length=10, verbose_name='年份(如：乙巳年)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('title', models.CharField(max_length=50, verbose_name='職稱')),
                ('name', models.CharField(max_length=50, verbose_name='姓名')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Donation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.CharField(max_length=10, verbose_name='年份(如：乙巳年)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(max_length=50, verbose_name='姓名')),
                ('amount', models.IntegerField(verbose_name='金額')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Light',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.CharField(max_length=10, verbose_name='年份(如：乙巳年)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('item', models.CharField(max_length=50, verbose_name='項目')),
                ('name', models.CharField(max_length=50, verbose_name='姓名')),
                ('payment_status', models.BooleanField(default=False, verbose_name='繳費狀態')),
                ('remark', models.TextField(blank=True, verbose_name='備註')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
